-- Seed catalog from Sonna's Patisserie's real signature items (desserts only — cloud-kitchen pivot).
insert into categories (name, slug, kind, sort_order) values
    ('Signature Cakes', 'signature-cakes', 'collection', 1),
    ('Cheesecakes', 'cheesecakes', 'collection', 2),
    ('Mousses & Desserts', 'mousses-desserts', 'collection', 3),
    ('Brownies & Travel Cakes', 'brownies-travel-cakes', 'collection', 4);

insert into products (name, slug, description, price_inr, category_id, is_eggless_available, is_featured) values
    ('Punjabi-Style Chocolate Classic', 'punjabi-chocolate-classic',
     'Our most-loved cake — dense chocolate sponge layered with silky ganache, made fresh every day. 1 kg.',
     1150, (select id from categories where slug = 'signature-cakes'), true, true),
    ('Chocolate Caramel Almond Brittle', 'chocolate-caramel-almond-brittle',
     'Dark chocolate infused with burnt caramel and crowned with crunchy almond brittle. 1 kg.',
     1250, (select id from categories where slug = 'signature-cakes'), true, true),
    ('Belgian Chocolate Truffle', 'belgian-chocolate-truffle',
     'Couverture Belgian chocolate truffle with an all-natural cocoa butter glaze. 1 kg.',
     1100, (select id from categories where slug = 'signature-cakes'), true, false),
    ('Fresh Fruit Chantilly', 'fresh-fruit-chantilly',
     'Light vanilla sponge, fresh seasonal fruit and clouds of Chantilly cream. 1 kg.',
     1050, (select id from categories where slug = 'signature-cakes'), true, false),
    ('Rasmalai Cake', 'rasmalai-cake',
     'Saffron-cardamom sponge soaked in rasmalai milk, finished with pistachio. 1 kg.',
     1200, (select id from categories where slug = 'signature-cakes'), true, true),
    ('Nutella Cheesecake', 'nutella-cheesecake',
     'Baked cheesecake generously topped with Nutella on a buttery biscuit base. 500 g.',
     950, (select id from categories where slug = 'cheesecakes'), true, true),
    ('Biscoff Cheesecake', 'biscoff-cheesecake',
     'Creamy baked cheesecake with a Lotus Biscoff spread crown and biscuit crumb. 500 g.',
     950, (select id from categories where slug = 'cheesecakes'), true, true),
    ('Classic Baked Cheesecake', 'classic-baked-cheesecake',
     'Slow-baked New York style cheesecake — rich, dense and just tangy enough. 500 g.',
     850, (select id from categories where slug = 'cheesecakes'), true, false),
    ('Lemon Cheese Mousse', 'lemon-cheese-mousse',
     'Bright lemon curd folded into airy cream-cheese mousse. Single serve cup.',
     350, (select id from categories where slug = 'mousses-desserts'), true, false),
    ('Dark Chocolate Mousse', 'dark-chocolate-mousse',
     'Intense single-origin dark chocolate mousse with a sea-salt whisper. Single serve cup.',
     320, (select id from categories where slug = 'mousses-desserts'), true, false),
    ('Tiramisu Cup', 'tiramisu-cup',
     'Espresso-soaked layers with mascarpone cream and cocoa dusting. Single serve cup.',
     380, (select id from categories where slug = 'mousses-desserts'), true, false),
    ('Fudgy Walnut Brownie Box', 'fudgy-walnut-brownie-box',
     'Six fudgy, crackle-top brownies loaded with toasted walnuts.',
     600, (select id from categories where slug = 'brownies-travel-cakes'), true, false),
    ('Almond Tea Cake', 'almond-tea-cake',
     'Buttery almond loaf that travels well — perfect with evening chai.',
     550, (select id from categories where slug = 'brownies-travel-cakes'), true, false),
    ('Dense Chocolate Loaf', 'dense-chocolate-loaf',
     'All-natural cocoa loaf cake, deeply chocolatey without frosting fuss.',
     650, (select id from categories where slug = 'brownies-travel-cakes'), true, false);
